import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import RadicalXlogo from '../assets/RadicalX.svg'
import Diamond from '../assets/Diamondblue.jpg'
import Coin from '../components/GoldCoin.jpg'
import Avatar from '../components/ellipse.jpg'
import Status from '../components/Statusgreen.jpg'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


{/* Navigation */}
      <nav>
        <ul style={{ height: '85px', backgroundColor: 'black', padding: '0px', display: 'flex', alignItems: 'center' }}>
          <li>
            {/* Logo */}
            <Link href="/">
              <Image src={RadicalXlogo} alt="Vercel Logo" width={100} height={85} style={{ marginLeft: '20px' }} />
            </Link>
          </li>

          {/* Mission LeaderBoard Rewards */}
          <div style={{ flex: 1, display: 'flex', justifyContent: 'center', alignItems: 'center' }}>
            <li>
              <Link href="./Mission" className={styles.Mission_LeaderBoard_Rewards}>🚀Missions</Link>
            </li>
            <li style={{ padding: '0 50px' }}>
              <Link href="./Leaderboard" className={styles.Mission_LeaderBoard_Rewards}>🏆Leaderboard</Link>
            </li>
            <li>
              <Link href="./Rewards" className={styles.Mission_LeaderBoard_Rewards}>💰Rewards</Link>
            </li>
          </div>

          {/* Diamonds */}
          <Link href="./diamondpage">
            <div className={styles.Diamond}>
              <Image src={Diamond} alt="Diamond" width={20} height={20} style={{ marginRight: 10 }} />
              2000
            </div>
          </Link>

            {/* Gold Coins */}
          <Link href="./Coinpage" >
            <div className={styles.Coin} style={{ margin: '0 10px' }}>
              <Image src={Coin} alt="Diamond" width={20} height={20} style={{ marginRight: 10, maxWidth: '100%', borderRadius: '50%' }} />
              11000
            </div>
          </Link>

          {/* Avartar and Status */}
          <Link href="/profile">
            <div className={styles.RoundImage}>
              <div className={styles.AvatarContainer}>
                <Image src={Avatar} alt="Avatar" />
                <Image src={Status} alt="Status" className={styles.StatusImage} />
              </div>
            </div>
          </Link>

        </ul>
      </nav> {/*Navigation bar End*/}


      {/* Footer */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
